spring:
  application:
    name: mysom
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  exposed:
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysom
    username: myuser
    password: mypassword
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: test
  exposed:
    generate-ddl: true
    show-sql: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysom
    username: myuser
    password: mypassword
server:
  port: 8080